Error: invalidoperationexception: no route in the route table matches the supplied values
Solution:
"                return RedirectToAction("Index");
" has been changed to "                    return RedirectToAction("Create");
".
And the reason for the temperory change which solves the error at the moment is the current routing configuration setup for test purpose in App_Start folder, RouteConfig class.