OnlineShop2Test prject has been added to the solution but it doesn't work at the moment.
Error: Exception thrown: 'System.InvalidOperationException' in EntityFramework.dll
An exception of type 'System.InvalidOperationException' occurred in EntityFramework.dll but was not handled in user code
No connection string named 'NavEcommerceDBfirstEntities_Model2OnlineStore2' could be found in the application config file.